pop-os/shop

- data/application.css
Adds Pop-based styling CSS to the `.badge` class so that the updates badge doesn't look like elementary anymore. As pretty as that is, it doesn't fit with Pop_OS.
> Add Pop-styling to updates badge

- data/application.css
This moves the update badge a bit lower down, and away from the top of the headerbar, giving it a bit of breathing room and visually linking it to the "Installed" label.
@cassidyjames Please do a quick review for the appearance of the badge. Since it's a single-line CSS change, this shouldn't need a full review.
> Tweak .badge margin

- src/Core/Houston.vala
- src/Views/Homepage.vala
- src/Widgets/Carousel/Carousel.vala
- src/Widgets/CategoryItem.vala
Sets Pop!_Shop up as a a client for the Pop! Houston server ([Deckard](https://github.com/pop-os/deckard)), and simplifies the homepage to just be the banner, a "featured" collection of up to 15 "Pop!_Picks", and the categories.
Before merging, we will need to:
To test, run Deckard locally like in its README, or get someone on your network to do so, and change `HOUSTON_API_URL` to the correct IP address/port combo.
> Pop!_Picks

- src/MainWindow.vala
Should help prevent blank GUIs when Pop_Shop loads on first run. 
I'm not sure how to go about testing this without spinning an entirely new ISO, so for now, it might be best to test this out and check for any reduction in functionality. If it works correctly, we can look at creating an ISO with this in it to see if it fixes the problem. 
@brs17 re feedback from Cass, things to watch are CPU usage when opening the Pop_Shop GUI.
> Refresh the cache when the GUI loads.

- src/Core/Package.vala
- src/Widgets/Carousel/CarouselItem.vala
This lets us use [the existing logic for author titles](https://github.com/pop-os/shop/blob/3c8f4ff54f15a3cadf9b45880fe92ab76e02b22b/src/Core/Package.vala#L177), which apps like GNOME Builder need since they set a "project group" but not a "developer".
This also drops the "The" from the fallback author name, so the fallbacks look a little cleaner. Upstream PR opened at https://github.com/elementary/appcenter/pull/694 so we should still get translations for free.
> Use abstracted author title on homepage

- src/Views/AppInfoView.vala
Before:
The button wouldn't allow resizing the window smaller than this.
After:
It ellipsizes the label
> Ellipsize UrlButton labels

- src/Views/Homepage.vala
- It wouldn't show because the homepage_loaded() signal was never executed
- and so the cache was never updated
- and thus the number of updates never displayed
Closes #85
> Fix the update badge icon

- src/Widgets/PackageRow.vala
From a UX standpoint, having rows selectable means that you can perform some
action on them while they're selected. There's also often an expectation that
you can select multiple items and perform the same action on all of them at
once. Neither of these statements is true for AppCenterPackageRows, so they
should not be selectable.
At one point we patched out their selectability, but it appears to have been
pulled back in, potentially from a sync with upstream. See discussion on
pop-os/gtk-theme#31
> Make AppCenterPackageRow objects non selectable

- data/styles/categories.css
This adds the elementary color equivalents to a couple of categories which look better with their colors, rather than using our own Pop colors.
Additionally, it uses darker colors for the Music and Apps categories, to help improve contrast and usability.
> Minor changes to CSS for Pop

- data/styles/application.css
New GNOME app icons don't always include a built-in stroke for background
protection. This means that they can sometimes become lost against light-colored
backgrounds and are difficult to see.
This adds a slight icon shadow is certain contexts where such an icon may
become hard to see, such as search results or app listings.
Before this change:
After:
> Add some background protection to Appcenter app listings

- data/styles/application.css
Makes the background of progressbar labels transparent, adds a bit of padding between the label and the progressbar itself, and sets the text color to be the same as other text within the banner.
Fixes pop-os/gtk-theme#364
> Progressbar labels

- data/styles/application.css
This is different from the upstream theme, and
causes pop-os/gtk-theme#360
Fixes pop-os/gtk-theme#360
> Make stack widgets transparent

- src/Core/Client.vala
This is causing WiFi connection issues on a lot of systems.
It's automatically installed whenever the user clicks "Update All".
> fix: Hide the backport-iwlwifi-dkms driver

- src/Core/Client.vala
- src/Widgets/AppContainers/AbstractPackageRowGrid.vala
This does not affect 19.10 builds at all, these are just lint issues caught by a newer valac
> Fix 20.04 builds

- debian/control
Adds a dependency for libflatpak-dev so that the Flatpak page in the new Repoman fork will work.
> build(deb): Add libflatpak-dev depends for Repoman

- src/Widgets/AppContainers/AbstractAppContainer.vala
This ensures that action buttons don't butt directly up against the progress bar.
Fixes #160
> fix: Add margin below progress bar

- data/styles/application.css
This ensures that the text of the install button stays readable even if the flowboxchild with the buttons ends up selected (e.g. if it is clicked).
Fixes #173
> fix(css): Ensure text stays readable

- src/Views/Homepage.vala
This fixes the duplicate steam items and makes steam default to the Pop version
Requires https://github.com/pop-os/steam/pull/2 and https://github.com/pop-os/appstream-data/pull/23
> Link to correct steam ID

- src/Core/UbuntuDriversBackend.vala
Fixes the display of the -server package, which should not display as an update
> fix: Compare NVIDIA package versions by parsed int

- src/Core/UbuntuDriversBackend.vala
Take 2
For whatever reason, Vala can parse a string that isn't a number, and return a non-zero number
Fixes #211
> fix: Hide extraneous NVIDIA packages

- data/styles/application.css
This pull request removes the off-color background that surrounds the app description and changelog for each app.
| | Before  | After |
| ------------- | ------------- | ------------- |
| Light | ![before_discord](https://user-images.githubusercontent.com/4069415/92335789-af021300-f09a-11ea-8ba6-0c5ae0cf86d9.png) | ![after_discord](https://user-images.githubusercontent.com/4069415/92335794-b9241180-f09a-11ea-8a91-f5e25c6905d7.png) |
| Dark | ![before_discord_dark](https://user-images.githubusercontent.com/4069415/92335798-c5a86a00-f09a-11ea-8d67-3285e4592783.png) | ![after_discord_dark](https://user-images.githubusercontent.com/4069415/92335804-cfca6880-f09a-11ea-970d-82bcc8ca1ac0.png) |
> Remove Backgrounds from App Text

- src/Core/UbuntuDriversBackend.vala
Since origin info is not available from the output of `ubuntu-drivers list`, I'm using a grep of `apt-cache policy` output to see if the package is available from us. I'm wondering if there's a better approach.
- `apt-cache show nvidia-driver-440` does not show any packages with a Pop origin
- `apt-cache policy nvidia-driver-440` does show a preferred package with `http://ppa.launchpad.net/system76/pop/ubuntu`
> fix: Hide NVIDIA drivers which do not have a Pop origin

- data/io.elementary.appcenter.service.in
- data/io.elementary.appcenter.timer
- data/io.elementary.appcenter.update-check.sh.in
- data/meson.build
- debian/control
- debian/pop-shop.install
- debian/pop-shop.links
- debian/pop-shop.postinst
Uses a systemd timer and a shell script to check for updates daily. On an update being found, a notification is displayed that will open the shop to the updates view on activation of the notification. This should stop reports of the shop using 2 GB RAM in the background when not in use.
> fix: Use systemd timer for update checks to eliminate background RAM usage

- src/Core/ScreenshotCache.vala
See https://github.com/elementary/appcenter/issues/1537
Without this screenshots for Popsicle fail to load (unless already cached in `~/.cache/io.elementary.appcenter`).
This should fix that, at the cost of having to download the screenshots each time since the cache doesn't know when the remote copy was last updated.
> Workaround screenshot fetch failing for packages like Popsicle

- data/styles/application.css
Currently in a dark theme (with dark button backgrounds), when a selected
row has a button on it, the text within that button is dark colored. With
this patch, the text should be colored based on what the theme specifies
for foreground text (usually "black" on light themes and "white" on
light themes) so that the text remains readable on dark
button backgrounds.
It was decided to make this change within the Pop_Shop codebase instead of against the theme because I can't find any instances of buttons with dark backgrounds on selected activatable rows anywhere else in our default apps which leads me to believe this is a pattern specific to Pop_Shop, but I can modify this there instead if I missed something. 
Fixes pop-os/gtk-theme#516
> fix(css): ensure that text buttons in selected rows remain legible
